### ISSUE TITLE
Minimize force scaling capacity timeout

### ISSUE THREAD

**Issue by docktermj** [Senzing/aws-cloudformation-database-cluster#10]
When forcing a scaling event, there is a period of time that RDS waits before scaling.  The default is 300 seconds.  This default should be changed to 10 seconds.  This can probably be done in the `LambdaFunctionSetRdbTimeoutAction` resource.

To see this value in the AWS RDS console:

1. Visit https://console.aws.amazon.com/rds/home#databases:
1. Choose  a database can be chosen
1. Click "Actions" > "Set Capacity"
1. In "If a seamless scaling point cannot be found with the specified seconds, forcibly scale capacity by closing client connections." there is a entry field to specify how many seconds to wait before forcing a scaling event.

### boto3

See "modify_current_db_cluster_capacity" in https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html

### Documentation

1. See "SecondsBeforeTimeout" in https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyCurrentDBClusterCapacity.html
1. Searchable keywords:
    1. ForceApplyCapacityChange

**Comment by roncewind** [comment]
Seems the documentation is incorrect.  When attempting to set this to 10 seconds, I receive the following error: 

```
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the ModifyDBCluster operation: The SecondsBeforeTimeout 10 is not valid. SecondsBeforeTimeout must be between 60 to 600.
```

so, I will try 60 seconds.

**Comment by roncewind** [comment]
@brianmacy, @docktermj  looks like I need some admin support to make this happen
```
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ModifyCurrentDBClusterCapacity operation: User: arn:aws:sts::511635769224:assumed-role/Ron-db-333-IamRoleLambda-18J21GAKWH9WS/Ron-db-333-lambda-set-rdb-timeout-action is not authorized to perform: rds:ModifyCurrentDBClusterCapacity on resource: arn:aws:rds:us-east-2:511635769224:cluster:ron-db-333-aurora-senzing-libfeat-cluster because no identity-based policy allows the rds:ModifyCurrentDBClusterCapacity action
```

**Comment by roncewind** [comment]
60 seconds doesn't seem to show up in the UI and it's odd that 10-600s is documented everywhere, but generates an error when calling the API.  There's the off chance that we're not calling the right API it's a difference between `modify_current_db_cluster_capacity` and `modify_db_cluster` the "current" API gives an error if it's called while the database is being created, so I'll have to create a new lambda function that will get called once a database is created.

**Comment by roncewind** [comment]
Found where it's documented that it's 60-600 Seconds:  https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ScalingConfiguration.html

**Comment by roncewind** [comment]
PR merged
