### ISSUE TITLE
Support for specifying vpc cidr instead of the default

### ISSUE THREAD

**Issue by ssasidharanwp** [Senzing/aws-cloudformation-database-cluster#26]
**Is your feature request related to a problem? Please describe.**
Currently when we use the cf template to create a new cluster, it always creates in 10.0.0.0/16 cidr which creates a problem for routing with multiple clusters

**Describe the solution you'd like**
Ability to provide the first 2 parts of the cidr or the entire cidr as a parameter to the cloudformation with a default value to support existing customers

**Describe alternatives you've considered**
Fork this repo and have our version which would require us to constantly check for changes and update the forked cf

**Additional context**

**Comment by roncewind** [comment]
Our CFTs are offered as examples.  we actively encourage you to take them and modify them as your own.  In an effort to keep our examples as straightforward as possible, we won't be making the requested change at this time.  Thank you.
