### ISSUE TITLE
Support for bigger private subnet 

### ISSUE THREAD

**Issue by ssasidharanwp** [Senzing/aws-cloudformation-database-cluster#27]
**Is your feature request related to a problem? Please describe.**
Currently each private subnet size is 256(/24). So it allows for a total of 512 containers in a cluster with the 2 subnets. But we have about 400 stream loaders and 200 redoer running, which requires at-least 600 ips

**Describe the solution you'd like**
Add parameter to support providing of the cidr size or update the size to accommodate 1024 containers(/23)

**Describe alternatives you've considered**
Forking the repo and updating the cf ourselves which requires constant sync with the master

**Additional context**

**Comment by roncewind** [comment]
PR merged, release created, pushed to S3
