### ISSUE TITLE
Migrate from senzing/postgresql-client container to senzing/init-postgresql container

### ISSUE THREAD

**Issue by docktermj** [Senzing/aws-cloudformation-database-cluster#56]
Currently the Cloudformation template uses multiple instance of `senzing/postgresql-client` to:

- Create the database schema in one or more databases 
    - Uses `psql` https://github.com/Senzing/postgresql-client/blob/main/rootfs/app/wait-and-run-postgres-client.sh
- Insert a Senzing Configuration into SYS_CFG and SYS_VARS via database INSERT.
    - https://github.com/Senzing/postgresql-client/blob/main/rootfs/app/insert-senzing-configuration.sql

https://github.com/Senzing/aws-cloudformation-database-cluster/blob/6f1555353545b8e48a958252e7074cae5744896b/cloudformation.yaml#L1202-L1372

With the new [init-postgresql](https://github.com/Senzing/init-postgresql), this can be simplified to one invocation of the `senzing/init-postgresql` container.

A single instance of `senzing/init-postgresql` will:

- Create the database schema in one or more databases 
- Insert a Senzing Configuration into SYS_CFG and SYS_VARS via Senzing ConfigManager.

An example of this in a docker-compose.yaml file is:

https://github.com/Senzing/docker-compose-demo/blob/a57dcba761662ad9bb77a701d4496225e8cfd021/resources/postgresql/docker-compose-rabbitmq-postgresql.yaml#L214-L246

The key is the `SENZING_ENGINE_CONFIGURATION_JSON` environment variable which specifies all of the databases that need to be initialized.

**Comment by roncewind** [comment]
PR merged, release created
