### ISSUE TITLE
S3 error: Access Denied 

### ISSUE THREAD

**Issue by christianswanepoel** [Senzing/aws-cloudformation-database-cluster#6]
See error on execution - please advise
S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

(Exciting to start off right using the split deployment approach)

**Comment by christianswanepoel** [comment]
Workaround: 
Uploading cloudformation.yaml manually worked as expected.

**Comment by docktermj** [comment]
@christianswanepoel I verified that the files on S3 aren't publicly available.   Have requested from our AWS admin to make them public.

**Comment by docktermj** [comment]
@christianswanepoel I just verified that they are now public.
